[package]
name = "graphql-server"
edition = "2021"
version = "0.1.0"

[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.94"
juniper = "0.16.1"
reqwest = { version = "0.12.9", features = ["json"] }
wasmcloud-component = "0.2.0"
wit-bindgen = "0.36.0"
